### ISSUE TITLE
Serial Configuration conflicting information

### ISSUE THREAD

**Issue by Xenon-2510** [bigtreetech/BIGTREETECH-SKR-mini-E3-#1]
I have attempted to compile my own version of Marlin using the firmware configurations laid out in the firmware readme. The Serial Port configuration is conflicting as the text is different to the image displayed. Please can you amend to show which is correct. (please see attached image)

Thanks. 

![Screenshot_20190706_173155](https://user-images.githubusercontent.com/52606199/60758878-535e7480-a014-11e9-9ce0-f6732e35223d.jpg)

**Comment by Msq001** [comment]
oh， so sorry for that， I have unified it.  In fact, Both this two configurations can be used normally.

**Comment by Xenon-2510** [comment]
Thank you for correcting it 😊
