### ISSUE TITLE
Fan0 and Fan1 mixed compared to stock Ender 3

### ISSUE THREAD

**Issue by weakset** [bigtreetech/BIGTREETECH-SKR-mini-E3-#16]
This board is advertised ad drop-in replacement, but if user copies wiring from stock, his part cooling fan is always 100% and marlin controls the case fan. You have to switch their places to control correct fan.

**Comment by weakset** [comment]
The source of this mixup:
In stock board both fan headers are connected and work identical. We tested this with multimeter instead of trying to find schematics. That is bad design for case fan, it should always be on even if part cooling is off or low.

SKR-mini-E3 did try to fix this, but it isn't well documented. Users should be advised which header fans should be connected to,  because they are different than on stock board.

**Comment by The-slunk** [comment]
So the only difference is that the parts fan and control box fan headers have new switched?

**Comment by weakset** [comment]
They did fix one fan header so that it is always 100%, but they didn't label it on pcb or tell that to users any other way. And using stock wiring as reference as most people do, you'd most likely plug parts fan to that 100% header.

Good fix, but bad documentation.

**Comment by weakset** [comment]
I did finally find the documentation. There actually is manual on github, but wiring page doesn't help you. You have to know how to read Pins page.
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/blob/master/Hardware/SKR%20MINI%20E3%20V1.0%20manual.pdf

So technically the solution was RTFM, I still suggest you document it easier to understand.
