### ISSUE TITLE
Non-stop continuous beeping with Ender3 12864 LCD buzzer, when powered with USB

### ISSUE THREAD

**Issue by delafer** [bigtreetech/BIGTREETECH-SKR-mini-E3-#17]
After flashing a new firmware version and testing in usb mode, connected via pc-usb, so with 5V only power supply and without any sensors / motors attached -> Ender3 12864 LCD buzzer produces constant continuous beeping. After resetting / flashing original stock firmware (supplied on sd card) continuous beeping sound disappears. 
I have commented out #define SPEAKER in configuration.h file, it doesn't help.
I have a latest marlin version from 25.08.2019 with https://github.com/MarlinFirmware/Marlin/pull/15026 bugfix, it doesn't help also.
behavior of stock firmware powered via usb in test mode is different and stock firmware ,doesn't produce any annoing constant buzzer sounds, if skr mini e3 is turned on.

**Comment by CineXMike** [comment]
What was the issue?
I am having the same problem.

**Comment by delafer** [comment]
> What was the issue?
> I am having the same problem.

Du you have skr e3 mini or skr e3 dip version with removable drivers ?

**Comment by retikulumx** [comment]
Hi. I'm having the same issue. And yes, the dip version with TMC2209 on it.
Is it a TMC related problem? It seems so since the beeping starts before Marlin init.
