### ISSUE TITLE
CHOPPER_DEFAULT_12V vs CHOPPER_DEFAULT_24V

### ISSUE THREAD

**Issue by jaceknyc** [bigtreetech/BIGTREETECH-SKR-mini-E3-#7]
Looking through the configs enabling hybrid mode and ran across this:

https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/blob/master/firmware/Marlin-2.0.x-SKR-Mini-E3/config/examples/Creality/Ender-3/Configuration_adv.h#L1798

Should that be `CHOPPER_DEFAULT_24V` for an Ender 3 for the SKR Mini E3 or should we leave it set to 12V?

**Comment by thisiskeithb** [comment]
It should be `CHOPPER_DEFAULT_24V` since the Ender-3 & Ender-5 are 24v printers.

**Comment by jaceknyc** [comment]
Closing in favor of https://github.com/MarlinFirmware/Marlin/pull/14851
